### ISSUE TITLE
can not compile wemos_lua_base.ino

### ISSUE THREAD

**Issue by sfranzyshen** [lhsantos/wemos_lua_base#1]
Linux 32 Arduino 1.8.2 Esp8266 Ver 2.3.0

```
Archiving built core (caching) in: /tmp/arduino_cache_876583/core/core_esp8266_esp8266_d1_mini_CpuFrequency_160,UploadSpeed_921600,FlashSize_4M1M_95e7e4a0a6e5c203e8268065460b634e.a
sketch/lbaselib.c.o: In function `luaB_select':
sketch/lbaselib.c:398: undefined reference to `__ctype_ptr__'
sketch/lbaselib.c:400: undefined reference to `strspn'
sketch/lbaselib.c.o: In function `luaB_tonumber':
sketch/lbaselib.c:81: undefined reference to `strspn'
sketch/lbaselib.c.o: In function `b_str2int':
sketch/lbaselib.c:56: undefined reference to `strspn'
sketch/ldblib.c.o: In function `db_getuservalue':
sketch/ldblib.c:72: undefined reference to `_impure_ptr'
sketch/ldblib.c.o:(.text.db_debug+0x18): undefined reference to `fgets'
sketch/ldblib.c.o: In function `db_debug':
sketch/ldblib.c:402: undefined reference to `fgets'
sketch/ldo.c.o: In function `seterrorobj':
sketch/ldo.c:719: undefined reference to `longjmp'
sketch/ldo.c.o: In function `luaD_throw':
sketch/ldo.c:719: undefined reference to `longjmp'
sketch/ldo.c.o: In function `f_parser':
sketch/ldo.c:719: undefined reference to `setjmp'
sketch/ldo.c.o: In function `luaD_rawrunprotected':
sketch/ldo.c:719: undefined reference to `setjmp'
sketch/lobject.c.o: In function `intarith':
sketch/lobject.c:96: undefined reference to `strtof'
sketch/lobject.c.o: In function `l_str2dloc':
sketch/lobject.c:251: undefined reference to `strtof'
sketch/lobject.c.o:(.text.luaO_str2num+0xc): undefined reference to `strpbrk'
sketch/lobject.c.o:(.text.luaO_str2num+0x14): undefined reference to `localeconv'
sketch/lobject.c.o: In function `l_str2int':
sketch/lobject.c:323: undefined reference to `strpbrk'
sketch/lobject.c.o: In function `l_str2d':
sketch/lobject.c:283: undefined reference to `localeconv'
sketch/lobject.c.o: In function `luaO_tostring':
sketch/lobject.c:378: undefined reference to `strspn'
sketch/lobject.c:378: undefined reference to `localeconv'
sketch/lstrlib.c.o:(.text.str_format+0x54): undefined reference to `memchr'
sketch/lstrlib.c.o: In function `addquoted':
sketch/lstrlib.c:912: undefined reference to `memchr'
sketch/lstrlib.c:912: undefined reference to `localeconv'
sketch/lstrlib.c:912: undefined reference to `memchr'
sketch/lstrlib.c.o: In function `str_find_aux':
sketch/lstrlib.c:611: undefined reference to `strpbrk'
sketch/lstrlib.c:620: undefined reference to `memchr'
sketch/lvm.c.o:(.text.l_strcmp+0x0): undefined reference to `strcoll'
sketch/lvm.c.o: In function `l_strcmp':
sketch/lvm.c:711: undefined reference to `strcoll'
/home/user/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/lib/libm.a(lib_a-ef_fmod.o):(.literal+0x0): undefined reference to `__ieee754_remainderf'
/home/user/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/lib/libm.a(lib_a-ef_fmod.o): In function `__ieee754_fmodf':
ef_fmod.c:(.text+0x36): undefined reference to `__ieee754_remainderf'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board WeMos D1 R2 & mini.
```

**Comment by sfranzyshen** [comment]
Updated to using github clone instead of board manager ... compiled fine! 
Nice Job!

**Comment by alfacentauri-32** [comment]
compiling on arduino ide 1.8.2 windows 10 gives the following error:
`Arduino:1.8.2 (Windows 10), Tarjeta:"LOLIN(WEMOS) D1 R2 & mini, 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

Archiving built core (caching) in: C:\Users\yagot\AppData\Local\Temp\arduino_cache_613115\core\core_esp8266_esp8266_d1_mini_CpuFrequency_80,UploadTool_esptool,UploadSpeed_921600,FlashSize_4M3M_76aef60bdc7c54248819011cea68ebf7.a
sketch\lbaselib.c.o: In function `luaB_select':

sketch/lbaselib.c:398: undefined reference to `__ctype_ptr__'

sketch/lbaselib.c:400: undefined reference to `strspn'

sketch\lbaselib.c.o: In function `luaB_tonumber':

sketch/lbaselib.c:81: undefined reference to `strspn'

sketch\lbaselib.c.o: In function `b_str2int':

sketch/lbaselib.c:56: undefined reference to `strspn'

sketch\ldblib.c.o: In function `db_getuservalue':

sketch/ldblib.c:72: undefined reference to `_impure_ptr'

sketch\ldblib.c.o:(.text.db_debug+0x18): undefined reference to `fgets'

sketch\ldblib.c.o: In function `db_debug':

sketch/ldblib.c:402: undefined reference to `fgets'

sketch\ldo.c.o: In function `seterrorobj':

sketch/ldo.c:719: undefined reference to `longjmp'

sketch\ldo.c.o: In function `luaD_throw':

sketch/ldo.c:719: undefined reference to `longjmp'

sketch\ldo.c.o: In function `f_parser':

sketch/ldo.c:719: undefined reference to `setjmp'

sketch\ldo.c.o: In function `luaD_rawrunprotected':

sketch/ldo.c:719: undefined reference to `setjmp'

sketch\lobject.c.o: In function `intarith':

sketch/lobject.c:96: undefined reference to `strtof'

sketch\lobject.c.o: In function `l_str2dloc':

sketch/lobject.c:251: undefined reference to `strtof'

sketch\lobject.c.o:(.text.luaO_str2num+0xc): undefined reference to `strpbrk'

sketch\lobject.c.o:(.text.luaO_str2num+0x14): undefined reference to `localeconv'

sketch\lobject.c.o: In function `l_str2int':

sketch/lobject.c:323: undefined reference to `strpbrk'

sketch\lobject.c.o: In function `l_str2d':

sketch/lobject.c:283: undefined reference to `localeconv'

sketch\lobject.c.o: In function `luaO_tostring':

sketch/lobject.c:378: undefined reference to `strspn'

sketch/lobject.c:378: undefined reference to `localeconv'

sketch\lstrlib.c.o:(.text.str_format+0x54): undefined reference to `memchr'

sketch\lstrlib.c.o: In function `addquoted':

sketch/lstrlib.c:912: undefined reference to `memchr'

sketch/lstrlib.c:912: undefined reference to `localeconv'

sketch/lstrlib.c:912: undefined reference to `memchr'

sketch\lstrlib.c.o: In function `str_find_aux':

sketch/lstrlib.c:611: undefined reference to `strpbrk'

sketch/lstrlib.c:620: undefined reference to `memchr'

sketch\lvm.c.o:(.text.l_strcmp+0x0): undefined reference to `strcoll'

sketch\lvm.c.o: In function `l_strcmp':

sketch/lvm.c:711: undefined reference to `strcoll'

c:/users/yagot/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/lib\libm.a(lib_a-ef_fmod.o):(.literal+0x0): undefined reference to `__ieee754_remainderf'

c:/users/yagot/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/lib\libm.a(lib_a-ef_fmod.o): In function `__ieee754_fmodf':

ef_fmod.c:(.text+0x36): undefined reference to `__ieee754_remainderf'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compilando para la tarjeta WeMos D1 mini.
`
